### PR TITLE
Rejected promises does not free their rooms

### PR DESCRIPTION
**Pull request by swarthy**
If promise was rejected, `v.Promise.promise.isFulfilled()` return `false`

### CODE REVIEW

**Comment by samccone** [comment]
boom, thank you @swarthy :+1: 

awesome PR

**Comment by swarthy** [comment]
You're welcome!
Please, update npm package, if possible

**Comment by samccone** [comment]
will do :)

**Comment by swarthy** [comment]
Thanks a lot!

**Comment by samccone** [comment]
v0.2.8 is out :clap:

**Pull request merged**
